spec:
  template:
    spec:
      containers:
        -
          resources:
            requests:
              cpu: "0.050"
              memory: 128Mi
            limits:
              cpu: "0.200"
              memory: 256Mi
          env:
            - name: JAVA_OPTIONS
              value: '-Xms128m -Xmx256m'
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'